apiVersion: v1
kind: Pod
metadata:
  name: data-loader
  namespace: kubeflow
spec:
  containers:
  - name: data-loader
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /mnt/data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-pvc
  restartPolicy: Never
